# This workflow tests Sqitch's PostgreSQL engine on all supported versions of
# YugabyteDB. It runs for pushes and pull requests on the `main`, `develop`,
# `**postgres**`, `**yugabyte**`, and `**engine**` branches.
name: 💫 Yugabyte
on:
  push:
    branches: [main, develop, "**engine**", "**postgres**", "**yugabyte**" ]
  pull_request:
    branches: [main, develop, "**engine**", "**postgres**", "**yugabyte**" ]
jobs:
  Yugabyte:
    strategy:
      matrix:
        include:
          # curl https://registry.hub.docker.com/v2/repositories/yugabytedb/yugabyte/tags\?page_size\=10000 | jq '.results[].name' | sort
          - { version: '2.19', tag: 2.19.0.0-b190 }
          - { version: '2.18', tag: 2.18.1.0-b84  }
          - { version: '2.17', tag: 2.17.3.0-b152 }
          - { version: '2.16', tag: 2.16.6.0-b43  }
          - { version: '2.15', tag: 2.15.3.2-b1   }
          - { version: '2.14', tag: 2.14.11.0-b35 }
          - { version: '2.13', tag: 2.13.2.0-b135 }
          - { version: '2.12', tag: 2.12.12.0-b12 }
          - { version: '2.11', tag: 2.11.2.0-b89  }
          - { version: '2.8',  tag: 2.8.12.0-b5   }
          - { version: '2.6',  tag: 2.6.20.0-b10  }
    name: 💫 Yugabyte ${{ matrix.version }}
    runs-on: ubuntu-latest
    steps:
      - name: Setup YugabyteDB cluster
        id: yugabyte
        # https://github.com/yugabyte/yugabyte-db-action/issues/5
        # uses: yugabyte/yugabyte-db-action@master
        uses: jameshartig/yugabyte-db-action@master
        with:
          yb_image_tag: "${{ matrix.tag }}"
      - uses: actions/checkout@v4
      - name: Setup Perl
        id: perl
        uses: shogo82148/actions-setup-perl@v1
        with: { perl-version: latest }
      - name: Cache CPAN Modules
        uses: actions/cache@v3
        with:
          path: local
          key: perl-${{ steps.perl.outputs.perl-hash }}
      - run: cpm install --verbose --show-build-log-on-failure --no-test --with-recommends --cpanfile dist/cpanfile
      - run: cpm install --verbose --show-build-log-on-failure --no-test --with-recommends DBD::Pg
      - name: prove
        env:
          PERL5LIB: "${{ github.workspace }}/local/lib/perl5"
          LIVE_PG_REQUIRED: true
          SQITCH_TEST_PG_URI: db:pg://yugabyte@localhost:${{ steps.yugabyte.outputs.ysql_port }}/
        run: prove -lvr t/pg.t
